config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, controllers: {sessions: 'admins/sessions'}
  devise_for :users, controllers: {sessions: 'users/sessions'}

  resources :posts do
    resources :comments
  end

  root 'posts#index'
  get '/fernanda', to: 'posts#new'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates_presence_of :title, :message=>"El campo esta vacio"
    validates_length_of :body, :in=> 10..400,:message=>"longitud no valida"
    belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
  
    @posts = Post.all
  end
  
  
  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if user_signed_in?
      if cannot? :edit, @post
    flash[:alert]= "No tiene permisos para editar"
    redirect_to :action =>'index',:format=>'html'
    end 
    end
  
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        flash[:success]="Se guardo correctamente"
        format.html{redirect_to @post}
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
         format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        flash[:alert]="Su post no se guardo"
        
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        #format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        #format.json { render :show, status: :ok, location: @post }
       flash[:success]="Se actualizo correctamente"
        format.html{redirect_to @post}
      else

        #format.html { render :edit }
        #format.json { render json: @post.errors, status: :unprocessable_entity }
        flash[:alert]="Su post no se actualizo correctamente"
        format.html{render :edit}
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      #format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
      flash[:alert]="Se ha eliminado"
        format.html{redirect_to posts_url}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>  

   <section class="row">
    <div class="small-4 columns">
      <div class="actions">
        <%= f.submit 'Aceptar', :class => 'button round btn' %>
      </div>    
    </div>
  </section>
<% end %>

app/views/posts/_navigationbar.html.erb
<nav class="top-bar" style="background-color: #000000;" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
    <h1><marquee class= "Tpost">
      <%= link_to 'POST',controller: '/posts', action: 'index'%>
    </marquee></h1>
  </li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
      <li class="has-dropdown not-click"><a href="#">Menu</a>
        <ul class="dropdown">
        <li class="parent-link show-for-small-only"<a parent-link js-generated href="">Inicio</a></li>
        <li><label>Post</label></li>
        <% if admin_signed_in?%>
          <li><%= link_to'Lista',controller:'/posts',action:'index'%></li>
        <% else %>
          <li><%= link_to'Lista',controller:'/posts',action:'index'%></li>
          <li><%= link_to'Nuevo',controller:'/posts',action:'new'%></li>
        <%end%>
        <!--<li><label>Back</label></li>
        <li><label><%=link_to 'Back', posts_path %></label></li>-->    
      </ul>
      </li>
      <li class="divider"></li>
    </ul>


    <!-- Right Nav Section -->
    <ul class="navbar-text pull-right right">

    <% if user_signed_in?%>
      <li><a>Logged ini as <strong id= "Entrar"><%=current_user.email%></strong>.</a></li>
      <li class="divider"></li>
      <li class="has-dropdown not-click"><a href="">User</a>
        <ul class="dropdown">
          <li class="parent-link show-for-small-only"<a parent-link js-generated href="">Start</a></li>
          <li><label>Post</label></li>
          <li><%=link_to 'Editar perfil', edit_user_registration_path, :class=>'navbar-link'%></li>
          <li><%=link_to "Salir", destroy_user_session_path, method: :delete, :class=>'navbar-link'%></li>
        </ul>
      </li>        
    <% end %>


    <% if admin_signed_in?%>
      <li><a>Logged in as <strong id= "login"><%= current_admin.email %></strong>.</a></li>
      <li class="divider"></li>
      <li class="has-dropdown not-click"><a href="">Administrador</a>
        <ul class="dropdown">
          <li class="parent-link show-for-small-only"<a parent-link js-generated href="">Start</a></li>
          <li><label>Post</label></li>
          <li><%=link_to 'Editar perfil', edit_admin_registration_path, :class=>'navbar-link'%></li>
          <li><%=link_to "Salir", destroy_admin_session_path, method: :delete, :class=>'navbar-link'%></li>
        </ul>
      </li>        
    <% end %>


      <% if !admin_signed_in? && !user_signed_in?  %> 
      <li><a><%=link_to "Registrarte", new_user_registration_path,:class=>'navbar-link'%></a></li>
      <li><%=link_to "Iniciar sesion", new_user_session_path,:class=>'navbar-link'%></li>
      
      <% end %> 
      
    </ul>
  </section>
</nav>

app/views/posts/edit.html.erb
<section class="margins">
	<h1>Editing Post</h1>

	<%= render 'form' %>

	<%= link_to 'Mostrar', @post %> |
	<%= link_to 'Back', posts_path %>
</section>

app/views/posts/index.html.erb
  <h1>Lista de post</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Cuerpo</th>
      <% if admin_signed_in? %>
      <th>email</th>
      <% end %>
      <th colspan="3"></th>
    
    


    </tr>
  </thead>

  <tbody>

  <% @posts.each do |post| %>
      <% if user_signed_in? %>
      <% if post.user_id == current_user.id %>
      <tr>
        <td><%= post.title %></td>
        <td>
          <%if post.body %>
            <a href="#" data-reveal-id="post-<%=post.id%>">Ver mas</a>
              <div id="post-<%=post.id%>" class="reveal-modal" data-reveal>
                <%=post.body%>
                <a class="close-reveal-modal">&#215;</a>          
            </div>
          <%end%>
        </td>
        <td><%= link_to 'Mostrar', post %></td>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'Eliminar', post, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
      <% end %>
    <% end %>





    <% if admin_signed_in? %>
      <tr>
        <td><%= post.title %></td>
        <td>
          <%if post.body %>
            <a href="#" data-reveal-id="post-<%=post.id%>">Ver mas</a>
              <div id="post-<%=post.id%>" class="reveal-modal" data-reveal>
                <%=post.body%>
                <a class="close-reveal-modal">&#215;</a>          
            </div>
          <%end%>
        </td>
        <% if admin_signed_in? %>
        <td><%= User.find(post.user_id).email%></td>
        <%end%>
        <td><%= link_to 'Mostrar', post %></td>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'Eliminar', post, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
      <% end %>
    <% end %>




  </tbody>
</table>

app/views/posts/new.html.erb
<section class="margins">
	<h1>New Post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>
</section>

app/views/posts/show.html.erb
<section class="margins">
  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @post.body %>
  </p>

  <div id="comments">
    <%=render :partial => @post.comments.reverse %>
  </div>

  <%= form_for([@post, Comment.new], remote: true) do |f|%>
    <p><%=f.label :body, "Nuevo comentario" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit "Agregar comentario", :class => 'button round btn' %>
    </p>
  <% end %>

  <%= link_to 'Editar', edit_post_path(@post) %> |
  <%= link_to 'Atras', posts_path %>
</section>